#!/bin/bash

# 1. Küsi kasutajalt ees- ja perenimi
read -p "Sisesta oma eesnimi: " eesnimi
read -p "Sisesta oma perenimi: " perenimi

# 2. Looge kasutajanimi
kasutajanimi=$(echo "$eesnimi.$perenimi" | tr '[:upper:]' '[:lower:]')

# 3. Loo kasutaja süsteemis
sudo useradd -m -s /bin/bash -p $(openssl passwd -1 "Parool1!") -c "Kasutaja $eesnimi $perenimi" $kasutajanimi

# Kontrolli, kas kasutaja loomine oli edukas
if [ $? -eq 0 ]; then
    echo "Kasutaja $kasutajanimi loodi edukalt."
else
    echo "Kasutaja loomine ebaõnnestus!"
fi
